# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org3 - Grading Lab
  # ---------------------------------------------------------------------------
  - Name: GradingLab
    Domain: gradinglab.example.com
    EnableNodeOUs: true
    Template:
      Count: 10
      SANS:
        - localhost
    Users:
      Count: 10
