global:
  scrape_interval: 1s
  external_labels:
    monitor: "devopsage-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.example.com:9443"]
  - job_name: "peer0_miningcompany"
    static_configs:
      - targets: ["peer0.miningcompany.example.com:9444"]
  - job_name: "peer0_cuttingcompany"
    static_configs:
      - targets: ["peer0.cuttingcompany.example.com:9445"]
  - job_name: "peer0_gradinglab"
    static_configs:
      - targets: ["peer0.gradinglab.example.com:9446"]
  - job_name: "peer0_jewelrymaker"
    static_configs:
      - targets: ["peer0.jewelrymaker.example.com:9447"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
